### YamlMime:Architecture
metadata:
  title: WordPress on Azure
  titleSuffix: Azure Architecture Center
  description: Learn about multiple hosting options to deploy a highly scalable and secure installation of WordPress.
  author: vjirovsky
  ms.author: vjirovsky
  ms.date: 04/18/2023
  ms.topic: example-scenario
  ms.service: architecture-center
  ms.subservice: example-scenario
  ms.category:
    - web
  ms.custom:
    - web-apps
    - scalability
    - example-scenario
  social_image_url: /azure/architecture/example-scenario/infrastructure/media/secure-scalable-wordpress.png
name: Scalable and secure WordPress on Azure
azureCategories:
  - web
summary: Learn about multiple hosting options to deploy a highly scalable and secure installation of WordPress.
products:
  - azure-cdn
  - azure-key-vault
  - azure-load-balancer
  - azure-virtual-network
  - azure-vm-scalesets
thumbnailUrl: /azure/architecture/browse/thumbs/secure-scalable-wordpress.png
content: |
   [!include[](wordpress-overview-content.md)]
