### YamlMime:Architecture
metadata:
  title: Implement a Zero Trust Network for Web Applications by Using Azure Firewall and Azure Application Gateway
  description: Protect web apps by implementing Zero Trust security in virtual networks. Use Azure Firewall and Azure Application Gateway in networks to maximize protection.
  author: erjosito
  ms.author: jomore
  ms.date: 06/16/2025
  ms.topic: conceptual
  ms.subservice: architecture-guide
  ms.category:
    - networking
  ms.custom: arb-web
name: Implement a Zero Trust network for web applications by using Azure Firewall and Azure Application Gateway
azureCategories:
  - networking
  - security
summary: Protect web apps by implementing zero-trust security in virtual networks. Use Azure Firewall and Azure Application Gateway in networks to maximize protection.
products:
  - azure-application-gateway
  - azure-firewall
  - azure-virtual-network
  - azure-virtual-wan
  - azure-web-application-firewall
thumbnailUrl: /azure/architecture/browse/thumbs/application-gateway-before-azure-firewall-architecture-thumbnail.png
content: |
   [!INCLUDE[](application-gateway-before-azure-firewall-content.md)]
