### YamlMime:Architecture
metadata:
  title: Firewall and Application Gateway for virtual networks
  titleSuffix: Azure Example Scenarios
  description: Learn about options and best practices for using Azure Firewall and Azure Application Gateway security in virtual networks.
  author: erjosito
  ms.date: 06/26/2020
  ms.topic: conceptual
  ms.service: architecture-center
  ms.subservice: example-scenario
  ms.custom:
    - fcp
    - example-scenario
  ms.category:
    - networking
name: Firewall and Application Gateway for virtual networks
azureCategories:
  - networking
summary: Learn about options and best practices for using Azure Firewall and Azure Application Gateway security in virtual networks.
products:
  - azure
  - azure-expressroute
  - azure-firewall
  - azure-storage
  - surface
  - vs
thumbnailUrl: /azure/architecture/browse/thumbs/decision-tree.png
content: |
   [!include[](firewall-application-gateway-content.md)]
