### YamlMime:Architecture
metadata:
  title: Azure Arc-Enabled Server Configurations
  description: Use Azure Arc to extend Azure Resource Manager capabilities to Windows and Linux machines on any infrastructure.
  author: basimolimajeed
  ms.author: bamajeed
  ms.date: 04/29/2022
  ms.topic: conceptual
  ms.service: azure-architecture-center
  ms.subservice: reference-architecture
  ms.category:
    - hybrid
    - management-and-governance
  ms.custom:
    - linux-related-content
name: Manage configurations for Azure Arc-enabled servers
azureCategories:
  - hybrid
  - management-and-governance
summary: Use Azure Arc to extend Azure Resource Manager capabilities to Windows and Linux machines on any infrastructure.
products:
  - azure-arc
  - azure-monitor
  - azure-policy
  - azure-resource-manager
  - azure-virtual-machines
thumbnailUrl: /azure/architecture/browse/thumbs/azure-arc-hybrid-config.png
content: |
   [!include[](azure-arc-hybrid-config-content.md)]
