### YamlMime:Architecture
metadata:
  title: Line of Business Application using App Service Environment v3
  titleSuffix: Azure Architecture Center
  description: Learn about deploying line of business applications with an internal App Service Environment v3 while considering networking boundaries, devops, management, and more. 
  author: cykreng
  ms.author: cykreng
  ms.date: 05/11/2022
  ms.topic: conceptual
  ms.service: architecture-center
  ms.subservice: example-scenario
azureCategories:
  - compute
  - security
  - management-and-governance
products:
  - azure-app-service
name: Deploy Line of Business Applications using App Service Environment v3
summary: Learn about deploying line of business applications with an internal App Service Environment v3 while considering networking boundaries, devops, management, and more. 
thumbnailUrl: /azure/architecture/browse/thumbs/architecture-line-of-business-internal-app-service-environment-v3.png
content: |
  [!include[](line-of-business-internal-app-service-environment-v3-content.md)]