### YamlMime:Architecture
metadata:
  title: Tenancy model for SaaS applications
  description: This article describes the application tenancy models available to Software as a Service (SaaS) application builders.
  author: fredderf204
  ms.author: mifrie
  ms.date: 09/18/2020
  ms.topic: conceptual
  ms.service: architecture-center
  ms.subservice: azure-guide
azureCategories:
  - storage
products:
  - azure-storage
name: Tenancy models for SaaS applications
summary: This article describes the application tenancy models available to Software as a Service (SaaS) application builders.
thumbnailUrl: /azure/architecture/browse/thumbs/mixed-tenant.png
content: |
  [!include[](application-tenancy-content.md)]