### YamlMime:Architecture
metadata:
  title: Enterprise deployment using App Services Environment
  titleSuffix: Azure Reference Architectures
  description: Recommended architecture for deploying an enterprise application using App Services Environment.
  author: dsk-2015
  ms.date: 05/08/2020
  ms.topic: conceptual
  ms.service: architecture-center
  ms.subservice: reference-architecture
  ms.category:
    - management-and-governance
    - featured
  ms.custom:
    - reference-architecture
name: Enterprise deployment using App Services Environment
azureCategories:
  - management-and-governance
  - featured
summary: Recommended architecture for deploying an enterprise application using App Services Environment.
products:
  - azure
  - azure-bastion
  - azure-firewall
  - azure-monitor
  - azure-pipelines
  - azure-portal
  - azure-rbac
  - github
  - sql-server
  - vs
  - windows
thumbnailUrl: /azure/architecture/browse/thumbs/standard-ase-deployment.png
content: |
   [!include[](ase-standard-deployment-content.md)]
