### YamlMime:Architecture
metadata:
  title: Build a Multi-agent Workflow Automation Solution with Semantic Kernel
  description: Learn how to build scalable automation pipelines where multiple AI agents collaborate through a central API orchestrator, with persistent learning capabilities and automated deployment processes for enterprise-grade task automation.
  author: gpickett
  ms.author: gpickett
  ms.date: 6/16/2025
  ms.topic: solution-idea
  ms.collection: ce-skilling-ai-copilot
  ms.subservice: solution-idea
azureCategories:
  - ai-machine-learning
products:
  - ai-services
  - azure-cosmos-db
name: Build a multi-agent workflow automation solution with Semantic Kernel
summary: Learn how to build scalable automation pipelines where multiple AI agents collaborate through a central API orchestrator, with persistent learning capabilities and automated deployment processes for enterprise-grade task automation.
thumbnailUrl: /azure/architecture/browse/thumbs/multi-agent-workflow-automation.png
content: |
  [!INCLUDE[](Multi-agent-workflow-automation-content.md)]
