
metadata:
  title: Multi-agent workflow automation
  description: Learn how to build scalable automation pipelines where multiple AI agents collaborate through a central API orchestrator, with persistent learning capabilities and automated deployment processes for enterprise-grade task automation.
  author: gpickett
  ms.author: gpickett
  ms.date: 6/16/2025
  ms.topic: conceptual
  ms.subservice: ai-ml
azureCategories:
  - AI agents
products:
  - Semantic Kernel
  - Azure Foundry
  - Azure Cosmos DB
name: Multi-agent workflow automation
summary: Learn how to build scalable automation pipelines where multiple AI agents collaborate through a central API orchestrator, with persistent learning capabilities and automated deployment processes for enterprise-grade task automation.
thumbnailUrl: /azure/architecture/browse/thumbs/Multi-agent-workflow-automation.png
content: |
  [!INCLUDE[](Multi-agent-workflow-automation-content.md)]
