### YamlMime:Architecture
metadata:
  title: Manage Microsoft365 tenant configuration with Microsoft365DSC and Azure DevOps
  titleSuffix: Azure Reference Architectures
  description: Manage Microsoft365 tenant configuration with Microsoft365DSC and Azure DevOps. 
  author: desmay
  ms.author: desmay
  ms.date: 10/18/2022
  ms.topic: conceptual
  ms.service: architecture-center
  ms.subservice: example-scenario
azureCategories:
  - management-and-governance
  - devops
products:
  - azure-devops
  - azure-key-vault
  - azure-virtual-machines-windows
  - m365
  - ms-graph
name: Manage Microsoft365 tenant configuration with Microsoft365DSC and Azure DevOps
summary: Manage Microsoft365 tenant configuration with Microsoft365DSC and Azure DevOps.
thumbnailUrl: /azure/architecture/browse/thumbs/Manage-Microsoft365-with-Microsoft365DSC-and-Azure-DevOps.png
content: |
  [!include[](manage-microsoft-365-tenant-configuration-microsoft365dsc-azure-devops-content.md)]