### YamlMime:Architecture
metadata:
  title: Customer IT environment and the threats
  titleSuffix: Azure Reference Architectures
  description: Placeholder description.
  article: fcp
  author: rudneir2
  ms.author: ruolivei
  ms.date: 04/25/2022
  ms.topic: conceptual
  ms.service: architecture-center
  ms.subservice: reference-architecture
azureCategories:
  - integration
  - security
products:
  - azure
  - azure-sentinel
name: Customer IT environment and the threats
summary: Placeholder summary.
thumbnailUrl: /azure/architecture/browse/thumbs/customer-it-environment-threats-thumbnail.png
content: |
  [!include[](customer-it-environment-threats-content.md)]