### YamlMime:Architecture
metadata:
  title: OpenCensus on Azure with Application Insights
  description: This article describes an architecture that uses Azure Functions for Python, Azure Event Hubs, and Azure Service Bus to monitor an end-to-end distributed system.
  author: raliouat
  ms.author: raoufaliouat
  ms.date: 06/19/2023
  ms.topic: conceptual
  ms.service: architecture-center
  ms.subservice: azure-guide
products:
  - azure-application-insights
  - azure-event-hubs
  - azure-functions
  - azure-service-bus
  - azure-monitor
azureCategories:
  - security
name: OpenCensus on Azure with Application Insights
summary: This article describes an architecture that uses Azure Functions for Python, Azure Event Hubs, and Azure Service Bus to monitor an end-to-end distributed system.
thumbnailUrl: /azure/architecture/browse/thumbs/opencensus-with-application-insights.png
content: |
  [!include[](opencensus-with-application-insights.md)]
