### YamlMime:Architecture
metadata:
  title: Centralized app configuration and security
  titleSuffix: Azure Solution Ideas
  author: sowmyans
  ms.date: 05/13/2020
  description: Use Azure App Configuration and Azure Key Vault to create a centralized and secured configuration service for apps.
  ms.custom: fcp
  ms.service: architecture-center
  ms.subservice: solution-idea
  ms.category:
    - security
    - management-and-governance
name: Centralized app configuration and security
azureCategories:
  - security
  - management-and-governance
summary: Use Azure App Configuration and Azure Key Vault to create a centralized and secured configuration service for apps.
products:
  - aspnet
  - azure
  - azure-functions
  - vs
  - windows
thumbnailUrl: /azure/architecture/browse/thumbs/appconfig-development.png
content: |
   [!include[](appconfig-key-vault-content.md)]
