### YamlMime:Architecture
metadata:
  title: CI/CD for Azure Web Apps
  titleSuffix: Azure Solution Ideas
  author: doodlemania2
  ms.date: 12/16/2019
  description: Learn how to create web apps using ASP.NET, Java, Node.js, or PHP and deliver value faster to your customers with a CI/CD pipeline.
  ms.custom: 'acom-architecture, devops, continuous integration, continuous delivery, CI/CD, continuous deployment, interactive-diagram, pricing-calculator, is-deployable, ''https://azure.microsoft.com/solutions/architecture/azure-devops-continuous-integration-and-continuous-deployment-for-azure-web-apps/'''
  ms.service: architecture-center
  ms.category:
    - devops
    - web
    - featured
  ms.subservice: solution-idea
  social_image_url: /azure/architecture/solution-ideas/articles/media/azure-devops-continuous-integration-and-continuous-deployment-for-azure-web-apps.png
name: CI/CD for Azure Web Apps
azureCategories:
  - devops
  - web
  - featured
summary: Learn how to create web apps using ASP.NET, Java, Node.js, or PHP and deliver value faster to your customers with a CI/CD pipeline.
products:
  - azure-application-insights
  - azure-devops
  - azure-web-apps
thumbnailUrl: /azure/architecture/browse/thumbs/azure-devops-continuous-integration-and-continuous-deployment-for-azure-web-apps.png
content: |
   [!include[](azure-devops-continuous-integration-and-continuous-deployment-for-azure-web-apps-content.md)]
