### YamlMime:Architecture
metadata:
  title: Back up on-premises applications and data to cloud
  titleSuffix: Azure Solution Ideas
  author: doodlemania2
  ms.date: 12/16/2019
  description: Back up on-premises applications and data with Azure Backup and Blob storage applications. Read documentation on implementing these archiving solutions today.
  ms.custom: 'acom-architecture, bcdr, ''https://azure.microsoft.com/solutions/architecture/backup-archive-on-premises-applications/'''
  ms.service: architecture-center
  ms.category:
    - storage
    - hybrid
  ms.subservice: solution-idea
name: Back up on-premises applications and data to cloud
azureCategories:
  - storage
  - hybrid
summary: Back up on-premises applications and data with Azure Backup and Blob storage applications. Read documentation on implementing these archiving solutions today.
products:
  - azure
  - azure-backup
  - dotnet
thumbnailUrl: /azure/architecture/browse/thumbs/backup-archive-cloud-application.png
content: |
   [!include[](backup-archive-on-premises-applications-content.md)]
