### YamlMime:Architecture
metadata:
  title: Globally distributed applications using Cosmos DB
  titleSuffix: Azure Solution Ideas
  author: t2kx
  ms.date: 02/09/2020
  description: Guarantee access to users around the world with the high-availability and low-latency capabilities built into Microsoft global datacenters.
  ms.custom: 'acom-architecture, app-dev, Cosmos DB, ''https://azure.microsoft.com/solutions/architecture/globally-distributed-mission-critical-applications-using-cosmos-db/'''
  ms.service: architecture-center
  ms.category:
    - databases
    - management-and-governance
  ms.subservice: solution-idea
  social_image_url: /azure/architecture/solution-ideas/articles/media/globally-distributed-mission-critical-applications-using-cosmos-db.png
name: Globally distributed applications using Cosmos DB
azureCategories:
  - databases
  - management-and-governance
summary: Guarantee access to users around the world with the high-availability and low-latency capabilities built into Microsoft global datacenters.
products:
  - azure-cosmos-db
  - azure-traffic-manager
thumbnailUrl: /azure/architecture/browse/thumbs/globally-distributed-mission-critical-applications-using-cosmos-db.png
content: |
   [!include[](globally-distributed-mission-critical-applications-using-cosmos-db-content.md)]
