### YamlMime:Architecture
metadata:
  title: Lift and shift to containers with Azure Container Apps
  titleSuffix: Azure Solution Ideas
  description: Migrate existing web pps to containers deployed in Container Apps, a fully managed container service for building and deploying apps at scale in Azure.
  author: EdPrice-MSFT
  ms.author: architectures
  ms.date: 09/21/2022
  ms.topic: conceptual
  ms.service: architecture-center
  ms.subservice: solution-idea
  ms.category:
    - migration
    - containers
    - web
  ms.custom:
    - acom-architecture
    - app-dev
    - interactive-diagram
    - "https://azure.microsoft.com/solutions/architecture/migrate-existing-applications-to-container-apps"
  social_image_url: /azure/architecture/solution-ideas/articles/media/migrate-existing-applications-to-container-apps.png
name: Lift and shift to containers deployed in Azure Container Apps
azureCategories:
  - migration
  - containers
summary: Migrate existing web pps to containers deployed in Container Apps, a fully managed container service for building and deploying apps at scale in Azure.
products:
  - azure-active-directory
  - azure-container-registry
  - azure-app-service
thumbnailUrl: /azure/architecture/browse/thumbs/migrate-existing-applications-to-container-apps.png
content: |
   [!include[](migrate-existing-applications-to-container-apps.md)]
