### YamlMime:Architecture
metadata:
  title: Product recommendations for retail using Azure
  titleSuffix: Azure Solution Ideas
  author: doodlemania2
  ms.date: 12/16/2019
  description: Aggregate customer data into complete profiles. Use advanced Azure machine learning models to provide predictive insights on simulated customers.
  ms.custom: 'acom-architecture, artificial intelligence, solution architectures, Azure, ai gallery, interactive-diagram, ''https://azure.microsoft.com/solutions/architecture/customer-360/'''
  ms.service: architecture-center
  ms.category:
    - analytics
  ms.subservice: solution-idea
  social_image_url: /azure/architecture/solution-ideas/articles/media/product-recommendations.png
name: Product recommendations for retail using Azure
azureCategories:
  - analytics
summary: Aggregate customer data into complete profiles. Use advanced Azure machine learning models to provide predictive insights on simulated customers.
products:
  - azure-blob-storage
  - azure-event-hubs
  - azure-hdinsight
  - azure-stream-analytics
  - power-bi
thumbnailUrl: /azure/architecture/browse/thumbs/product-recommendations.png
content: |
   [!include[](product-recommendations-content.md)]
