### YamlMime:Architecture
metadata:
  title: Serverless application architectures using Event Grid
  titleSuffix: Azure Solution Ideas
  author: doodlemania2
  ms.date: 12/16/2019
  description: 'Event Grid connects data sources and event handlers. For example, use Event Grid to instantly trigger a serverless function to run image analysis each time a new photo is added to a blob storage container.'
  ms.custom: 'acom-architecture, serverless, event-grid, azure, ''https://azure.microsoft.com/solutions/architecture/serverless-application-architectures-using-event-grid/'''
  ms.service: architecture-center
  ms.category:
    - developer-tools
  ms.subservice: solution-idea
  social_image_url: /azure/architecture/solution-ideas/articles/media/serverless-application-architectures-using-event-grid.png
name: Serverless application architectures using Event Grid
azureCategories:
  - developer-tools
summary: 'Event Grid connects data sources and event handlers. For example, use Event Grid to instantly trigger a serverless function to run image analysis each time a new photo is added to a blob storage container.'
products:
  - azure
thumbnailUrl: /azure/architecture/browse/thumbs/serverless-application-architectures-using-event-grid.png
content: |
   [!include[](serverless-application-architectures-using-event-grid-content.md)]
