### YamlMime:Architecture
metadata:
  title: Training and procedural guidance powered by mixed reality
  titleSuffix: Azure Solution Ideas
  author: doodlemania2
  ms.date: 12/16/2019
  description: 'Enable your team and employees to learn new processes and materials faster, with fewer errors, and greater confidence by providing persistent holographic instructions mapped to precise locations in their physical workspace.'
  ms.custom: 'acom-architecture, ai-ml, Azure Spatial Anchors, Azure Active Directory, Azure Cosmos DB, Azure App Service, Media Services, Microsoft HoloLens, Video Indexer, interactive-diagram, ''https://azure.microsoft.com/solutions/architecture/training-and-procedural-guidance-powered-by-mixed-reality/'''
  ms.service: architecture-center
  ms.category:
    - mixed-reality
  ms.subservice: solution-idea
  social_image_url: /azure/architecture/solution-ideas/articles/media/training-and-procedural-guidance-powered-by-mixed-reality.png
name: Training and procedural guidance powered by mixed reality
azureCategories:
  - mixed-reality
summary: 'Enable your team and employees to learn new processes and materials faster, with fewer errors, and greater confidence by providing persistent holographic instructions mapped to precise locations in their physical workspace.'
products:
  - azure
thumbnailUrl: /azure/architecture/browse/thumbs/training-and-procedural-guidance-powered-by-mixed-reality.png
content: |
   [!include[](training-and-procedural-guidance-powered-by-mixed-reality-content.md)]
