### YamlMime:Architecture
metadata:
  title: 'Transportation - Environment monitoring and supply chain'
  titleSuffix: Azure Example Scenarios
  description: Learn how to use Azure IoT for environment monitoring and supply chain optimization
  author: onaim-msft
  ms.date: 04/09/2021
  ms.topic: conceptual
  ms.service: architecture-center
  ms.subservice: example-scenario
  ms.category:
    - iot
  ms.custom:
    - fcp
    - example-scenario
name: 'Transportation - Environment monitoring and supply chain'
azureCategories:
  - iot
summary: Learn how to use Azure IoT for environment monitoring and supply chain optimization
products:
  - azure-functions
  - azure-iot
  - azure-storage
  - azure-machine-learning
  - azure-databricks
thumbnailUrl: /azure/architecture/browse/thumbs/environment-monitor-supply-chain.png
content: |
   [!include[](vertical-environment-monitor-supply-chain-content.md)]
