### YamlMime:Architecture
metadata:
  title: Create a Gridwich environment
  titleSuffix: Azure Reference Architectures
  description: Use the ci_cd_ext_release or tf_destroy_env pipelines to create or delete cloud development or testing environments.
  author: doodlemania2
  ms.date: 11/12/2020
  ms.topic: reference-architecture
  ms.service: architecture-center
  ms.subservice: reference-architecture
  ms.custom:
    - fcp
name: Create a Gridwich environment
summary: Use the ci_cd_ext_release or tf_destroy_env pipelines to create or delete cloud development or testing environments.
products:
  - azure
thumbnailUrl: /azure/architecture/browse/thumbs/run-pipeline-dialog.png
content: |
   [!include[](create-delete-cloud-environment-content.md)]
