### YamlMime:Architecture
metadata:
  title: Gridwich local development environment setup
  titleSuffix: Azure Reference Architectures
  description: Set up a local development environment to work with Gridwich.
  author: doodlemania2
  ms.date: 11/12/2020
  ms.topic: reference-architecture
  ms.service: architecture-center
  ms.subservice: reference-architecture
  ms.custom:
    - fcp
name: Gridwich local development environment setup
summary: Set up a local development environment to work with Gridwich.
products:
  - azure
  - azure-devops
  - dotnet
  - github
  - windows
thumbnailUrl: ./thumbs/default.png
content: |
   [!include[](set-up-local-environment-content.md)]
