### YamlMime:Architecture
metadata:
  title: Check Resource Property with Deployment Scripts
  description: Use Deployment Scripts in ARM Templates/Bicep to await a resource's property desired state to help you orchestrate end-to-end deployments.
  author: jtracey93
  ms.author: jatracey
  ms.date: 12/29/2022
  ms.topic: conceptual
  ms.service: architecture-center
  ms.subservice: azure-guide
azureCategories:
  - devops
  - networking
products:
  - azure-resource-manager
  - azure-virtual-network
  - azure-virtual-wan
name: Check Resource Property with Deployment Scripts
summary: Use Deployment Scripts in ARM Templates/Bicep to await a resource's property desired state to help you orchestrate end-to-end deployments.
thumbnailUrl: /azure/architecture/browse/thumbs/deployment-scripts-property-check.png
content: |
  [!include[](deployment-scripts-property-check-content.md)]