### YamlMime:Architecture
metadata:
  title: Security for mission-critical workloads on Azure
  description: Reference architecture for a workload that is accessed over a public endpoint without additional dependencies to other company resources.
  author: calcof
  ms.author: pnp
  ms.date: 05/01/2022
  ms.topic: conceptual
  ms.service: architecture-center
  ms.subservice: reference-architecture
  ms.category:
    - databases
    - security
    - devops
name: Security for mission-critical workloads on Azure
azureCategories:
  - containers
  - databases
  - security
summary: Reference architecture for a workload that is accessed over a public endpoint without additional dependencies to other company resources.
products:
  - azure-rbac  
thumbnailUrl: /azure/architecture/browse/thumbs/mission-critical-online.png
content: |
   [!include[](mission-critical-security-content.md)]