name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 */24 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest
    #permissions:
      #issues: write
      #pull-requests: write

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-pr-stale: 14   
        stale-pr-message: >
          This pull request has been inactive for 14 days.
          If you are finished with your changes, don't forget to sign off. See the [contributor guide](https://review.docs.microsoft.com/en-us/help/contribute/contribute-how-to-write-pull-request-automation) for instructions.
        stale-pr-label: inactive

