### YamlMime:Architecture
metadata:
  title: 'Cloud Application Signaling - SignalR'
  titleSuffix: Azure Example Scenarios
  description: Learn how to use Azure SignalR for real time telemetry visualization and action
  author: falloutxAY
  ms.date: 4/19/2021
  ms.topic: conceptual
  ms.service: architecture-center
  ms.subservice: example-scenario
  ms.category:
    - iot
  ms.custom:
    - fcp
    - example-scenario
name: 'Cloud Application Signaling - SignalR'
azureCategories:
  - iot
summary: Learn how to use Azure SignalR for real time telemetry visualization and action
products:
  - azure-functions
  - azure-iot
thumbnailUrl: /azure/architecture/browse/thumbs/cloud-application-signaling.png
content: |
   [!include[](cloud-application-signaling-content.md)]
